import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use · Side Hustle Command Centre",
};

const INK = "#1E1E24";
const STONE = "#E8E4DC";
const BRONZE = "#7f6720";
const SURFACE_HI = "#FBF7EC";
const BORDER = "rgba(30,30,36,0.10)";
const TEXT_BODY = "#3A3A44";
const TEXT_MUTED = "#6B6A75";
const TEXT_SUBTLE = "#908F99";

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: STONE, color: INK }}>
      <nav
        className="px-6 py-4 flex items-center justify-between max-w-5xl mx-auto"
        style={{ borderBottom: `1px solid ${BORDER}` }}
      >
        <Link href="/" className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full" style={{ backgroundColor: BRONZE }} />
          <span className="font-semibold text-sm tracking-tight">Side Hustle Command Centre</span>
        </Link>
        <Link href="/" className="text-sm" style={{ color: TEXT_MUTED }}>
          ← Home
        </Link>
      </nav>

      <main className="px-6 py-16 max-w-2xl mx-auto">
        <p className="text-xs uppercase tracking-widest mb-3" style={{ color: BRONZE }}>
          Terms
        </p>
        <h1 className="text-3xl sm:text-4xl font-bold leading-tight mb-4">Terms of Use</h1>
        <div
          className="px-5 py-4 mb-10 rounded-xl text-sm"
          style={{ backgroundColor: SURFACE_HI, border: `1px solid ${BORDER}`, borderLeft: `3px solid ${BRONZE}`, color: TEXT_BODY }}
        >
          <p>
            <strong>Last updated 2026-04-21.</strong> These terms are under legal review. Questions?
            Email{" "}
            <a href="mailto:hello@thesteadysystem.com" style={{ color: BRONZE }} className="underline">
              hello@thesteadysystem.com
            </a>
            .
          </p>
        </div>

        <div className="space-y-8 text-base leading-relaxed" style={{ color: TEXT_BODY }}>
          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              What you're buying
            </h2>
            <p>
              Side Hustle Command Centre is a personalized, AI-generated business launch system
              delivered as access to a private online workspace. You pay once ($67 CAD at time of
              writing) and retain access to your workspace for as long as I continue to operate the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              No refunds
            </h2>
            <p>
              Because the product is a digital good delivered instantly via a private link, all sales
              are final. Once your workspace has been generated, no refunds are offered. If something
              goes wrong technically (you never received access, the workspace failed to generate),
              email me within 14 days and I'll fix it or refund you personally.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              AI-generated content
            </h2>
            <p>
              Your launch runway, content prompts, pricing recommendations, and AI coach responses
              are generated by artificial intelligence (Anthropic's Claude API). AI can be wrong,
              incomplete, or outdated. You are responsible for reviewing every suggestion before
              acting on it, publishing it, or sharing it with customers.
            </p>
            <p className="mt-3">
              Nothing in Side Hustle Command Centre is legal, financial, tax, medical, or
              professional advice. If you need advice in those areas, speak to a qualified
              professional in your jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              No guarantee of results
            </h2>
            <p>
              I cannot and do not guarantee that using Side Hustle Command Centre will cause your
              business to succeed, reach any specific revenue, or meet any specific goal. Outcomes
              depend on your effort, your market, your timing, and many factors outside of this
              product's control. Any figures, examples, or ranges shown in the product or on this
              site are illustrative, not promises.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Acceptable use
            </h2>
            <ul className="space-y-2 list-disc pl-5">
              <li>Don't share your workspace link publicly. It functions as a password.</li>
              <li>
                Don't use the AI coach to generate content that is illegal, harassing, hateful, or
                infringing on others' intellectual property.
              </li>
              <li>
                Don't attempt to reverse engineer, scrape, or resell access to the service.
              </li>
              <li>One workspace per purchase. Extra message packs cost $5 for 50 messages.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Your content
            </h2>
            <p>
              You retain ownership of anything you write or upload into your workspace (your
              business info, your revenue entries, your own notes). I don't claim ownership of your
              content and I won't use it to train models or sell it. See the{" "}
              <Link href="/privacy" style={{ color: BRONZE }} className="underline">
                Privacy Policy
              </Link>{" "}
              for how data is handled.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by applicable law, my total liability to you for any
              claim arising out of or relating to Side Hustle Command Centre is limited to the amount
              you paid for it. I am not liable for indirect, incidental, or consequential damages,
              including lost profits or lost business, even if such damages were foreseeable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Service changes
            </h2>
            <p>
              I may update the product, change features, or adjust pricing for new buyers at any
              time. Existing buyers keep access on the terms they purchased under.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Governing law
            </h2>
            <p>
              These terms are governed by the laws of British Columbia, Canada. Any dispute that
              can't be resolved by email will be handled in the courts of British Columbia.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3" style={{ color: INK }}>
              Contact
            </h2>
            <p>
              Questions, complaints, or just want to say hi? Email{" "}
              <a href="mailto:hello@thesteadysystem.com" style={{ color: BRONZE }} className="underline">
                hello@thesteadysystem.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8" style={{ borderTop: `1px solid ${BORDER}` }}>
          <p className="text-xs" style={{ color: TEXT_SUBTLE }}>
            Side Hustle Command Centre by The Steady System.{" "}
            <Link href="/privacy" className="hover:underline" style={{ color: TEXT_MUTED }}>
              Privacy
            </Link>
          </p>
        </div>
      </main>
    </div>
  );
}
